# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Praveen Sahu
title: Ph.D Candidate, Purdue University, West Lafayette, IN, USA
email: psahu@purdue.edu
# email_title: Email (Email title override)
phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: psahu
orcid_username: 0000-0002-0240-3108
googlescholar_username: P9D8edUAAAAJ

# Additional icon links
additional_links:
- title: Portfolio
  icon: fab fa-ello
  url: praveensahuatpurdue.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/1660775599024.jpg
about_content: | # this will include new lines to allow paragraphs
   Hi! I'm Praveen Sahu, a PhD Candidate at Purdue University, West Lafayette, in the School of Engineering Technology. I'm an applied scientist by training with a background in electrical engineering, but I have just enough expertise in biomedical sciences and data science to make trouble.
    -	Research and Development Engineer with a 4-year track record of advancing healthcare innovation through electroporation-based breast cancer therapies. Successful outcomes include the development of new clinically relevant treatments and next-generation 3D-printed microchannel-based electroporation devices.
    -	Subject-matter expertise in electroporation therapy, interdisciplinary research, and scientific communication, resulting in 4+ peer-reviewed publications, 10+ presentations, 1 IEEE research grant, and $75,000+ in fellowships.
    -	Leadership and project management experience in cross-functional teams and guiding collaborative projects from concept to end-to-end execution, leading to 2 collaborative publications and a semiconductor-based pH sensor.
    -	Product development and conducted market research analysis in a start-up ecosystem for 3+ years on IoT hardware development and supervised the deployment of over 1000+ air quality monitoring devices.

highlights: |
      -	**IEEE Fellowship**: Dielectrics and Electrical Insulation Society (DEIS) student fellowship and grant, 2023-2024 ($5,000).
      -	**Fellowship**: Recipient of Bilsland Dissertation Scholarship, Purdue University, 2023-2024 ($35,650).
      -	**Grants**: Recipient of Summer Research Grant (SGR), Purdue University, 2023 ($8,000). 
      -	**Fellowship**: Earned prestigious Ross Fellowship, Purdue University, 2021 ($35,012).
      -	**Award**: Best oral presentation (2nd Prize) at Electrostatic Society of America-ESA (2021), Best student presentation at INNCP Conference India (2021), Best student presentation award at ISSS conference, San Francisco (2016).

content:
  - title: Education
    layout: list
    content:
      - layout: top-left 
        title: Ph.D. in Electrical Engineering Technology with specialization in Cancer Treatment                 
        sub_title: Purdue University, West Lafyette, IN, USA
        caption: 2021 - Expected Summer 2024 
      - layout: top-left 
        title: Masters (Research) in Electrical Engineering with specialization in Microelectronics (Sensors)                  
        sub_title:  Indian Institute of Technology Madras (IIT Madras), Chennai, India
        caption: 2013 - 2017
      - layout: top-left
        title: Bachelor of Technology in Electronics with specialization in Design & Manufacturing 
        sub_title: Indian Institute of Information Technology Design & Manufacturing (IIIT DM), Kancheepuram, India            
        caption: 2009 - 2013

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Computation
        description: >
         -  Embedded C/C++, LabVIEW, MATLAB, Python, COMSOL (FEM), ImageJ

      - layout: left
        title: Data Visualization (Analytics)
        description: >
         -  Tableau, Power BI, Prism GraphPad, Excel Macros, Powerpoint
      
      - layout: left
        title: Circuit Design
        description: >
         -  NI LabVIEW, NI Circuit Simulation, Cadence PCB, Matlab Simulink, Sketchup, Proteus Design Suite, AutoCAD 

      - layout: left
        title: Product Management
        description: >
         -  Trello, RACI, Gantt Chart, DPR, Procurement, BOM, MPIs, Product Life Cycle 
      
      - layout: left
        title: Wet lab
        description: >
         -  Electroporation, Cell culture, Cell Toxicity and Metabolic Assay, Semiconductor Fabrication Processes

      - layout: left
        title: Prototyping
        description: >
         -  3D-printing, SolidWorks, Design for X (DFX), Design Verification and Validation 

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left 
        title: Efficacy of metformin and electrical pulses in breast cancer MDAMB-231 cells (Accepted).
        sub_title: Exploration of Targeted Anti-tumor Therapy, 2024
        caption: P Sahu, I Camarillo, R Sundararajan
        link: https://doi.org/10.37349/etat.2024.00204
      - layout: top-left 
        title: Rapid and Low-Cost Fabrication of Microfluidic Devices Using Liquid Crystals Display-Based 3D Printing.
        sub_title: International Mechanical Engineering Congress & Exposition (IMECE), 2022 
        caption: Y Shan, P Sahu, R Sundararajan, H Mao
        link: https://asmedigitalcollection.asme.org/IMECE/proceedings-abstract/IMECE2022/V02AT02A024/1156764
      - layout: top-left 
        title: Enhanced Antiproliferation Potency of Electrical Pulse-mediated Metformin and Cisplatin combination therapy on MDA-MB-231 cells
        sub_title: Applied Biochemistry and Biotechnology Journal, 2021  
        caption: P Sahu, I Camarillo, R Sundararajan
        link:  https://doi.org/10.1007/s12010-021-03723-5 
      - layout: top-left 
        title: Extraction of Key Features and Enhanced Prediction Framework of Breast Cancer Occurrence
        sub_title: IEEE International Conference on Trends in Electronics and Informatics (ICOEI), 2022
        caption : P Sahu, P Giri, R Sunkara, R Sundararajan
        link: https://ieeexplore.ieee.org/abstract/document/9777165/
      - layout: top-left 
        title: Electroporation-Mediated Metformin for Effective Anticancer Treatment of Triple Negative Breast Cancer Cells
        sub_title: 18th International Conference on Chemical sensing (ICCS), San Francisco, USA, Jun 2016
        caption : P Sahu, P Giri, I Camarillo, R Sundararajan
        link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=P9D8edUAAAAJ&citation_for_view=P9D8edUAAAAJ:qjMakFHDy7sC
      - layout: top-left 
        title: Estimation of nitrogen using pH-sensitive EISCAP sensor
        sub_title: Proceedings 2021 Annual Meeting of the Electrostatics Society of America, Jun 2021, 2021
        caption : P Sahu, E Bhattacharya, A Chadha
        link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=P9D8edUAAAAJ&citation_for_view=P9D8edUAAAAJ:d1gkVwhDpl0C

      - layout: top-left 
        title: Simultaneous Trapping and Measurement of Nitrogen in Kjeldahl Process
        sub_title: International Conference on Emerging Technologies in Agricultural Engineering (ETAE), IIT Kharagpur, India, Dec 2016
        caption : P Sahu, E Bhattacharya, A Chadha
        link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=P9D8edUAAAAJ&citation_for_view=P9D8edUAAAAJ:u-x6o8ySG0sC
 
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Electroporation-based Cancer Therapy Development, Purdue University
        sub_title: Graduate Research Assistant
        caption: Jun 2021 - Present
        description: | # this will include new lines to allow paragraphs
          -	Prepared research plan, design of experiment (DOR), analysis, and troubleshooting, particularly for optimization of electrical pulse parameters and drug delivery. Accomplished a 3-fold reduction in breast cancer cell viability.
          -	Engineered 3D printing microfluidic device to create single cell streamline (passively) for precision cell manipulation and biomedical applications. Achieved 100µm microchannel width at a much lower cost than lithography.
          -	Adapted and validated the use of 3D scaffold as an in vitro cancer drug testing platform under electroporation conditions (mimicking actual tissue structure). Led to a collaborative project yielding an award-winning presentation.
          -	Proficient in interdisciplinary skills, including metabolomics, proteomics, and cell biology studies. Specialized in conducting laboratory experiments: cell culture, cell toxicity, ROS, glucose, and clonogenic in vitro assays.

      - layout: left
        title: Ultima Genomics, Newark, California, USA
        sub_title: Research and Development Intern, Intrumentation Platform
        caption: Jun 2022 - Aug 2022
        link: https://www.ultimagenomics.com/
        description: | # this will include new lines to allow paragraphs
           -	Led the assembly of a cutting-edge bead loading system, drafted a Bill of Materials (BOM) and simplified Manufacturing Process Instructions (MPIs) to streamline production processes, contributing to a 33% reduction in assembly time.
           -	Evaluated the surface temperature of silicon wafer on chuck using a FLIR IR-based camera, eliminated reflectivity issues, and redesigned the flexible PCB heater, contributing to a 60-70% reduction in temperature variations.
           -	Investigated liquid level-sensor trigger volume detection, optimizing steady-state water volume to 30ml, resulting in leak-free bowl and improved fluidics testing for enhanced product reliability and efficiency.
           -	Prepared rapid prototype for a silicon wafers holder on an optical bench by stacking multilayer acrylic sheets cut to precise specifications using Glowforge™ laser cutter and reached a flatness of ±5-10µm.

      - layout: left
        title: Clairco, Bangalore, India
        sub_title: Product Manager (R&D)
        caption: Oct 2019 - Mar 2020 
        description: | # this will include new lines to allow paragraphs
          - 	Designed and developed a prototype for an Air Quality monitoring device, seamlessly integrating it with the Microsoft Azure IoT Platform. This innovation paved the way for enhanced data accessibility and real-time monitoring, leading to a 5% improvement in environmental data accuracy compared to Honeywell AQMs.
          - 	Strategic collaboration with a manufacturer to facilitate bulk production, successfully deploying over 1000 devices across India, contributing to initial market penetration.
      - layout: left
        title: Agrometrics, Hyderabad, India
        sub_title: Product Manager 
        caption: Aug 2018 - Dec 2018
        description: |
          -	Designed and executed custom Production Management and Quality Control software for Alsum Farms (USA). Utilized strategic project management tools: RACI and Gantt charts, achieving the first milestone within 3 months. 
          -	Led the deployment of a Business Intelligence System, leveraging the LinkFresh database; identified and optimized Key Performance Indicators (KPIs) for farm scheduling and in-house logistics, saving nearly 10% in revenue ($5 million).
      - layout: left
        title: Enfrien Innovations, Bangalore, India
        sub_title: Product Development Engineer (R&D)
        caption: Mar 2017 - Jul 2018, Apr 2020 - Oct 2020
        description: | # this will include new lines to allow paragraphs
          -	Developed and deployed ESP32 Wi-Fi-based indoor and streetlight dimming circuitry, incorporating ambient light sensing (LDR), real-time clock (RTC), and cloud-based control. Achieved potential energy savings of 20% per light.
          -	Conceptualized a standalone and modular Power Surge Protection Device (SPD), which can be plugged in with any device, including medical diagnosis devices. Tested on LED fixtures and reduced the damage by >90%. 
          -	Detailed project report (DPR) on the feasibility study of 550 MW Solar project for KfW (German Development Bank) in Maharashtra & Kerala: data-collection, survey methodology, capacity analysis.
          -	Secured contract finalization through direct negotiations and on-site production oversight during a vendor visit to Guangzhou, China
      - layout: left
        title: Indian Institute of Technology Ropar, Punjab, India
        sub_title: Research Intern
        caption: May 2012 - Jul 2012
        description: | # this will include new lines to allow paragraphs
         -  Centralized Data Acquisition system (DAQ) for measurement of power, force, vibration, and the temperature of a workpiece 
            on a Lathe Machine
      - layout: left
        title: Indian Institute of Information Technology, Kancheepuram
        sub_title: Product Design Lab
        caption: Jan 2012 -April 2012
        description: | # this will include new lines to allow paragraphs
         -   Developed a prototype of a portable washing machine (20 USD) for washing light clothes with a power consumption of less 
             than 100 W
      - layout: left
        title: Central Electronics Lab (BEL), Bangalore, India
        sub_title: Research Intern
        caption: Jan 2012 -April 2012
        description: | # this will include new lines to allow paragraphs
         -   Developed an application to extract and process the information from a GPS module utilizing a microcontroller for finding the 
            Geolocation of Commonwealth Games Baton
  - title: Semiconductor based Bio/Chem Sensor (MASTER'S THESIS)
    layout: list
    content:
      - layout: top-left 
        title: Estimation of Nitrogen (NH4+ & organic) leveraging pH-Sensitive Electrolyte Insulator Semiconductor Capacitor (EISCAP) Sensor
        link: https://github.com/psahuatpurdue/MasterThesis_IITM/blob/main/MS_Bio.pdf
        description: |
          -	Fabricated pH-sensitive Electrolyte Insulator Semiconductor Capacitor (EISCAP) microsensor and enabled the characterization for estimation of nitrogen in soil while reducing analysis time from 10 min to 90 sec per sample.
          -	Analyzed and established statistical correlation between pH vs. the amount of nitrogen in the soil (0-20 mg/L). 

  - title: Embedded System Development (Gold Medalist)
    layout: list
    content:
      - layout: top-left 
        title: Wireless relay-based centralized control and monitoring of appliances
        description: |
          -  Designed and integrated wireless relay-based centralized control and monitoring of appliances along with the direct transmission of residential energy consumption to the billing server using a GSM-based energy meter.  
  - title: Achievements and Awards
    layout: text
    content: |
      -  Fellowship: IEEE Dielectrics and Electrical Insulation Society (DEIS) student fellowship and grant, 2023 ($5,000.00).
      -  Fellowship: Bilsland dissertation scholarship by Purdue university, 2024 ($35,650.00).
      -  Grants: Research summer grant by Purdue university, 2023 ($8,000.00). 
      -  Fellowship: Prestigious Ross fellowship, Purdue university, 2021 ($35,012.25).
      -  Awards: Best oral presentation award (2nd Prize), Electrostatic Satiety of America (ESA), USA, 2021.
      -  Awards: Best student presentation award, INNCP Conference, India, 2021.
      -  Awards: Best student presentation award, ISSS conference, San Francisco, USA, 2016.
      -  Fully Funded master's by MHRD, Govt. of India, 2013-2017.
  
  - title: Leadership and Responsibilities
    layout: text
    content: | # this will include new lines to allow paragraphs
      -	Presented ideas and led the team at Indo-Swiss Academia-Industry Training (Top 10 Start-ups), 2018.
      -	Visited Guangzhou (China) to meet vendors and supervise production while concluding the negotiation in 2017.
      -	Co-led and secured a Top-100 start-up position at Bangalore Tech Summit (India) as a first round of funding.
      -	Brainstormed and mentored 5+ interns for COVID-19-related sterilizer prototype: UV-C-based currency and grocery.
      -	Served as a Teaching Assistant and guided undergraduate students in various courses and projects.
      -	Active member and affiliated with the Data Visualization Society, ISEBT (Electroporation Technologies), ESA, and IEEE.


  - title: Teaching Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
        - ECET 277 Analog Circuit Systems, Spring & Fall 2022, Spring 2023 
        - ECET 299 Embedded Systems, Spring & Fall 2022, Spring 2023


  - title: Relevant Courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Design of Monitoring & Diagnostic Systems.
      - Advanced Topics in Instrumentation
      - Embedded Systems.
      - Product Life cycle Management
      - Regulatory Approval of Biomedical Devices (Ongoing)
      - Microsensors 
      - Machine Learning
      - Big Data
      - Statistics
      - Optimization

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
